blank_issues_enabled: true
contact_links:
  - name: Duda rápida del equipo
    url: https://github.com/ninnarouge/kiran-gpy1102-gestion-de-proyectos-de-software/issues/new?template=duda.md
    about: Pregunta de git, alcance o la Eva 1
